# Hypothesis Testing

# #Question 1st 

In [1]:
import numpy as np
import pandas as pd 
from scipy.stats import  chi2_contingency



In [2]:
df = pd.read_csv('Cutlets.csv')
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
"it is an two sample t tail test.(two tail test)"
'Null Hypothesis = no difference between daimeter of cutle (diameter of both cutlet are equal')
'Alternate Hypothesis = there is a actual difference between daimeter of cutlet(diameter of both cutlet are not equal')
'alpha= 0.05

In [3]:
from scipy import stats

In [4]:
stats.ttest_ind(df['Unit A'],df['Unit B'])

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [ ]:
# if pvalue is less than alpha = we reject null hypothesis
# if pvalue is greater than alpha  = we are failde to reject null hyposthesis(accept alternate hypothesis)

In [ ]:
# so according to Hypothesis rule
#   p value = 0.047 & alpha = 0.05 it means p value for these problem statement is less than alpha so we reject null hypothesis it means there is a actual significance difference between the diameter of cutlet of these two sample.

# the diameter of the cutlet of two units (unit A, unit B) are not equal. there is a actual  Significance difference between their diameter.

# Question 2

In [5]:
 lab= pd.read_csv('LabTAT.csv')

In [6]:
lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [7]:
lab.shape

(120, 4)

In [ ]:
# it is an example of multiple sample so we use Anova test here.
#

In [ ]:
" H0 = the time taken by all laboratories are eual"
" Ha = the tiem taken by all laboratories are not equal it means time for atleast one lab is different"


In [8]:
stats.f_oneway(lab.iloc[:,0],lab.iloc[:,1],lab.iloc[:,2],lab.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
# applying hypothesis rule
" p value = 0.0 & alpha = 0.05  pvlaue is less than alpha so we reject null hypothesis it means the time taken by these all four laboratories is different."

# the time taken by all these 4 laboratories is different.

#  Question 3


In [9]:
# it is an equality test . so me use chi square test
'  Chi square test with Significance value = 0.05'

'  Chi square test with Significance value = 0.05'

In [10]:
BuyerRation= pd.read_csv('BuyerRatio (1).csv')

In [11]:
BuyerRation

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [12]:
dataarry = np.array([[50,142,131,70],[435,1523,1356,750]])

In [13]:
dataarry

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [14]:
chi2_contingency(dataarry)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

  chi2 stats vlaue = 1.59 / p_value = 0.66 / df= 3

In [15]:
# p value is greter than alpha so is less than pvalue

" failed to reject null hypothesis. (Accept Null hypothesis)"

' it means the proportion of female and male is equal.'

' it means the proportion of female and male is equal.'

# # Question  4

In [ ]:
'H0 = the defective error of  all 4 center is same
ha = the defective error of all 4 center is different(at lest defective error of one center is different)'

In [16]:
customerdata  = pd.read_csv('Costomer+OrderForm.csv')

In [17]:
customerdata

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [18]:
customerdata.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [19]:
customerdata.Phillippines.value_counts()




Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [20]:
customerdata.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [21]:
customerdata.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [22]:
customerdata.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [23]:
customerorderarray =np.array([[271,267,269,280],[29,33,31,20]])
customerorderarray

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [24]:
chi2_contingency(customerorderarray)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [25]:
"chi2 stats = 3.85 / p_value = 0.27 / df = 3"

'chi2 stats = 3.85 / p_value = 0.27 / df = 3'

In [ ]:
# alpha = 0.05 
#  p_value  is less than 0.05 so reject null hypothesis."

##  the defective error of all these 4 center is different.